# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-21 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20160512_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['title']},
        ),
    ]
