# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-15 20:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20161021_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='contact_1_email',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='contact_2_email',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='contact_2_name',
        ),
        migrations.AlterField(
            model_name='asset',
            name='contact_1_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
