# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170301_2226'),
        ('asset', '0006_auto_20170315_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='asset.Asset')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorized_assets', to='core.Category')),
            ],
        ),
    ]
