# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_assetcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='contact_1_name',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
