# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-21 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovosite', '0005_auto_20160512_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborganization',
            name='org_type',
            field=models.CharField(blank=True, choices=[('college', 'college'), ('department', 'department'), ('lab', 'lab'), ('research group', 'research group'), ('division', 'division'), ('other', 'other')], max_length=48),
        ),
    ]
