# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-17 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innovosite', '0006_auto_20161014_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborganization',
            name='org_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childorgs', to='innovosite.SubOrganization'),
        ),
        migrations.AlterField(
            model_name='suborganization',
            name='org_type',
            field=models.IntegerField(choices=[(0, 'college'), (1, 'department'), (2, 'lab'), (3, 'research group'), (4, 'division'), (5, 'other')], default=5),
        ),
    ]
