# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-15 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovouser',
            name='affiliation',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='innovouser',
            name='degree',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='innovouser',
            name='degree_type',
            field=models.IntegerField(blank=True, choices=[(0, 'No Degree'), (1, 'Associates'), (2, 'Bachelors'), (3, 'Masters'), (4, 'Doctorate')], default=0),
        ),
        migrations.AddField(
            model_name='innovouser',
            name='prev_affiliations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='innovouser',
            name='prev_positions',
            field=models.TextField(null=True),
        ),
    ]
